# Generated by Django 4.2.2 on 2023-06-29 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0006_userfavoriterecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite_recipes',
            field=models.ManyToManyField(related_name='favorite_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserFavoriteRecipe',
        ),
    ]
