# Generated by Django 4.2.2 on 2023-06-29 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0007_recipe_favorite_recipes_delete_userfavoriterecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shopping_card',
            field=models.ManyToManyField(related_name='shopping_card', to=settings.AUTH_USER_MODEL),
        ),
    ]
