# Generated by Django 4.2.2 on 2023-06-30 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0008_recipe_shopping_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='shopping_card',
        ),
        migrations.AddField(
            model_name='recipe',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='shopping_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
