# Generated by Django 4.2.2 on 2023-07-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_favorite_recipes_recipe_favorites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='favorites',
            new_name='users_favorite',
        ),
    ]
