# Generated by Django 4.2.2 on 2023-07-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='users_shopping_carts',
        ),
    ]
