# Generated by Django 4.2.2 on 2023-07-02 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0010_remove_recipe_users_shopping_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='users_shopping_carts',
            field=models.ManyToManyField(blank=True, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='В списке покупок у ...'),
        ),
    ]
