# Generated by Django 4.2.2 on 2023-07-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_users_shopping_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='users_favorite',
            new_name='users_favorites',
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient_in_recipe'),
        ),
    ]
